export * from './getPictures';
export * from './getSimilar';
export * from './getTrailer';
export * from './getRate';
export * from '../../../APIs/getMovieAPI';
export * from './saveMovieList';
export * from './savePicturesInState';
export * from './saveAdditionalData';
export * from '../../../APIs/getGenres'